services:
  web:
    image: laravel-with-redis-cluster-web:1.25
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    image: laravel-with-redis-cluster-php:8.3
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  redis-node-0:
    image: bitnami/redis-cluster:7.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  redis-node-1:
    image: bitnami/redis-cluster:7.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  redis-node-2:
    image: bitnami/redis-cluster:7.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  redis-node-3:
    image: bitnami/redis-cluster:7.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  redis-node-4:
    image: bitnami/redis-cluster:7.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

  redis-node-5:
    image: bitnami/redis-cluster:7.4
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDISCLI_AUTH=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=Index0:redis-node-0:6379:0:${REDIS_PASSWORD},Index1:redis-node-1:6379:0:${REDIS_PASSWORD},Index2:redis-node-2:6379:0:${REDIS_PASSWORD},Index3:redis-node-3:6379:0:${REDIS_PASSWORD},Index4:redis-node-4:6379:0:${REDIS_PASSWORD},Index5:redis-node-5:6379:0:${REDIS_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
